"use client"; // this is a client component
import Image from 'next/image'
import { useState } from "react";
import Collapse from './collapse.js'

export const state = {
  description: 'Generated by create next app',
}


function TakeProductPhotosForMe() {

  const [show, setShow] = useState(false)
  const changeShow = () => {
    setShow(!show)
  }

  return (
    <div>
      { show && <div> Yes, absolutely. A clean and great quality product photo will help a lot.  When you create a new product, instead of uploading your product photo, just choose the option to let our team take the photos for you. </div> }
      <button onClick={changeShow}>点我</button>
    </div>
  )
}

const bgPotions = {   
  backgroundPosition: 'left top, right top, right bottom, left bottom',
  backgroundSize: '15%, 15%, 15% 50%'
}
const gridPreview = [
  
]

export default function Home() {
  let [collapsesSwitch, toggleCollapseSwitch] = useState( [ false, true, false ] )
  /**
   * @description: switch the collapsesSwitch
   * @param {*} index
   * @return {*}
   */
  const handleToggleCollapseSwitch = () => {
    // toggleCollapseSwitch()
    collapsesSwitch[0] = !collapsesSwitch[0]
    console.log(collapsesSwitch ); 
  }
  let [firstCollapseSwitch, setFirstCollapseSwitch] = useState(false)
  const handleSetFirstCollapseSwitch = () => setFirstCollapseSwitch(!firstCollapseSwitch)
  let [secondCollapseSwitch, setSecondCollapseSwitch] = useState(false)
  const handleSetSecondCollapseSwitch = () => setSecondCollapseSwitch(!secondCollapseSwitch)
  let [thirdCollapseSwitch, setThirdCollapseSwitch] = useState(false)
  const handleSetThirdCollapseSwitch = () => setThirdCollapseSwitch(!thirdCollapseSwitch)
  return (
    <div className="flex min-h-screen flex-col items-center justify-between pt-6">
      <header className="z-10 w-full items-center justify-between text-sm lg:flex px-12">
        <div className="fixed bottom-0 left-0 flex h-48 items-end bg-gradient-to-t from-white via-white lg:static w-1/2 lg:h-auto ">
          <a
            className="pointer-events-none flex place-items-center gap-2 p-8 lg:pointer-events-auto lg:p-0"
            href=""
            rel=""
          >
            <Image
              src="/home/logo.png"
              alt="logo"
              width={40}
              height={40}
              priority
            />
              <span className='font-semibold '>AI ProShots</span>
          </a>
        </div>
        <nav className='flex flex-between gap-x-11 text-[1.125rem] '>
          <span className='cursor-pointer'> How it works </span>
          <span className='cursor-pointer'> Pricing </span>
          <span className='cursor-pointer'> Contact us </span>
          <span className='cursor-pointer'> Log in </span>
          <span className='cursor-pointer block bg-[--theme-blue] px-[60px] py-[3px] rounded-[50px] text-white'> Try it </span>
        </nav>
      </header>
      
      <article className='w-full flex flex-col items-center'>
        <span className='z-0 font-semibold text-[--theme-gray] text-[12.5rem]'> AI ProShots </span>
        <div className='z-50 relative w-full h-[4.1875rem] bg-[--theme-darkblue] h-16rem] top-[-5.3125rem] flex justify-around items-end'>
          <span className='text-base text-white'>Unleash the power of AI. </span>
          <span className='tittle-line h-[2px] w-40 bg-white mb-4'/>
        </div>
      </article>
      
      <div className='px-24 flex flex-col items-center'>
        <article className='font-semibold text-[3.4375rem] text-center '>
          <div>Revolutionize</div>
          your product photos with AI
        </article>

        <article className='max-w-[68.9375rem] py-20 grid grid-cols-2 items-stretch gap-x-[3.625rem]'>
          <div className=''>
            <Image
              className="h-[30rem] w-[30rem] rounded-[30px]"
              src="/home/product-demo.png"
              alt=""
              width={0}
              height={0}
              sizes='100%'
              priority
            />
          </div>
          <div className='flex flex-col gap-y-6'>
            <div className='w-full h-full border border-[#767676] border-solid rounded-[1.875rem] p-10 text-4xl'>
              My product on a soft surface with pillows and flowers. Luxury, bright.
            </div>
            <span className='text-white block bg-[--theme-darkblue] rounded-[30px] text-center py-5 font-medium text-4xl cursor-pointer'>Generate</span>
	
          </div>
        </article>
        
        {/* <div className="relative flex place-items-center before:absolute before:h-[300px] before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] z-[-1]">
          <Image
            className="relative dark:drop-shadow-[0_0_0.3rem_#ffffff70] dark:invert"
            src="/next.svg"
            alt=""
            width={180}
            height={37}
            priority
          />
        </div> */}

        {/* <div className="mb-32 grid text-center lg:max-w-[68.9375rem] lg:w-full lg:mb-0 lg:grid-cols-4 lg:text-left">
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`mb-3 text-2xl font-semibold`}>
              Docs{' '}
              <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
                -&gt;
              </span>
            </h2>
            <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
              Find in-depth information about Next.js features and API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=appdir-template-tw&utm_campaign=create-next-app"
            className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800 hover:dark:bg-opacity-30"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`mb-3 text-2xl font-semibold`}>
              Learn{' '}
              <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
                -&gt;
              </span>
            </h2>
            <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`mb-3 text-2xl font-semibold`}>
              Templates{' '}
              <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
                -&gt;
              </span>
            </h2>
            <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
              Explore the Next.js 13 playground.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=appdir-template&utm_campaign=create-next-app"
            className="group rounded-lg border border-transparent px-5 py-4 transition-colors hover:border-gray-300 hover:bg-gray-100 hover:dark:border-neutral-700 hover:dark:bg-neutral-800/30"
            target="_blank"
            rel="noopener noreferrer"
          >
            <h2 className={`mb-3 text-2xl font-semibold`}>
              Deploy{' '}
              <span className="inline-block transition-transform group-hover:translate-x-1 motion-reduce:transform-none">
                -&gt;
              </span>
            </h2>
            <p className={`m-0 max-w-[30ch] text-sm opacity-50`}>
              Instantly deploy your Next.js site to a shareable URL with Vercel.
            </p>
          </a>
        </div> */}

        <article className='max-w-[68.9375rem] py-20 grid grid-cols-[1fr_1fr_1fr] gap-x-[4rem] gap-y-10 pb-60' style={gridPreview}>
          <Image
            className="cursor-pointer h-auto w-full rounded-[30px] col-start-1 col-end-1"
            src="/home/custom-left-top-product.png"
            alt=""
            width={0}
            height={0}
            sizes='100%'
            priority
          />
          <Image
            className="cursor-pointer h-auto w-full rounded-[30px] col-start-1 col-end-1"
            src="/home/custom-left-bottom-product.png"
            alt=""
            width={0}
            height={0}
            sizes='100%'
            priority
          />
          {/* max-w-[220%] */}
          <Image
            className="max-w-[none] w-full block rounded-[30px] col-[2/4] row-[1/3] j"
            src="/home/default-product.png"
            alt=""
            width={0}
            height={0}
            sizes='100%'
            priority
          />
        </article>

        <article className='pb-80 max-w-[68.9375rem] w-full'>
          <p className="text-[3.4375rem] font-semibold text-center">How it works</p>
          {/* rounded-[40px] border-[3px] border-[--theme-black] */}
          {/* bg-[url('/home/border-left-top.png'),url('/home/border-top-right.png'),url('/home/border-right-bottom.png'),url('/home/border-left-bottom.png')] */}
          <div
            className="
              bg-no-repeat grid grid-cols-2 py-[3.3125rem]
              px-12 gap-y-12 gap-x-20 bg-[url('/home/border-left-top.png'),url('/home/border-top-right.png'),url('/home/border-right-bottom.png'),url('/home/border-left-bottom.png')] bg-left-top
            "
            style={bgPotions}
          >
            <div>
              <d className='flex items-center mb-6'>
                <span className='text-4xl mr-[2.625rem]'>Step 1</span>
                <Image
                  className="inline w-9 h-[1.875rem]"
                  src="/home/camera.png"
                  alt=""
                  width={0}
                  height={0}
                  sizes='100%'
                  priority
                />
              </d>
              <div className='text-2xl'>Submit your product image</div>
            </div>

            <div>
              <div className='flex items-center mb-6'>
                <span className='text-4xl mr-[2.625rem]'>Step 2</span>
                <Image
                  className="inline w-[1.875rem] h-7"
                  src="/home/pen.png"
                  alt=""
                  width={0}
                  height={0}
                  sizes='100%'
                  priority
                />
              </div>
              <div className='text-2xl'>Submit your product image</div>
            </div>

            <div>
              <div className='flex items-center mb-6'>
                <span className='text-4xl mr-[2.625rem]'>Step 3</span>
                <Image
                  className="inline w-9 h-9"
                  src="/home/setting.png"
                  alt=""
                  width={0}
                  height={0}
                  sizes='100%'
                  priority
                />
              </div>
              <div className='text-2xl'>Submit your product image</div>
            </div>

            <div>
              <div className='flex items-center mb-6'>
                <span className='text-4xl mr-[2.625rem]'>Step 4</span>
                <Image
                  className="inline w-[1.875rem] h-[1.875rem]"
                  src="/home/pic.png"
                  alt=""
                  width={0}
                  height={0}
                  sizes='100%'
                  priority
                />
              </div>
              <div className='text-2xl'>Submit your product image</div>
            </div>
          </div>
          <div className='text-2xl w-[18.75rem] h-14 rounded-[50px] text-white bg-[--theme-blue] flex justify-center items-center cursor-pointer mx-auto mt-[-1.875rem]'>Free to Try</div>
        </article>

        <article className='pb-80'>
          <p className='text-center text-[3.4375rem] row-start-1 col-start-1 col-end-2 pb-[3.125rem]'>AI ProShots vs. Others</p>
          <p className='text-center text-2xl pb-[5.3125rem]'>Real experiment done with the same image, same prompt, and same time.</p>
          <div className='grid grid-cols-2 gap-x-[6.5rem] pb-[8.25rem]'>
            <div>
              <div className='text-4xl text-center pb-4'>AI ProShots</div>
              <Image
                className="block w-auto rounded-[30px] col-start-2 col-end-2 row-start-1 row-end-3"
                src="/home/default-product.png"
                alt=""
                width={0}
                height={0}
                sizes='100%'
                priority
              />
            </div>
            <div>
              <div className='text-4xl text-center pb-4'>Another Website</div>
              <Image
                className="block w-auto rounded-[30px] col-start-2 col-end-2 row-start-1 row-end-3"
                src="/home/default-product.png"
                alt=""
                width={0}
                height={0}
                sizes='100%'
                priority
              />
            </div>
          </div>
          <div className='text-2xl pl-32'>AI ProShots is aimed to generate professional quality images.</div>
        </article>
      </div>


      <article className='text-white bg-[--bg-shallow-blue] w-full grid grid-cols-4 mb-32'>
        <div className='inline bg-[--bg-blue] col-span-3 pl-[4.625rem] pr-[3.125rem] py-14'>
          <p className='text-[3.4375rem]'>Why did the chicken cross the road?</p>
          <p className='text-[3.4375rem] pb-14'>To get our FREE tier!</p>
          <p className='text-4xl pb-[6.4375rem]'>
            Yep, you read that right! Free to start. Our free tier is so good, even chickens are crossing roads for it! 
          </p>
          <div className='rounded-[50px] h-[3.4375rem] bg-white w-[18.75rem] text-center text-black leading-[3.4375rem] text-2xl font-medium cursor-pointer'>Join Now</div>
        </div>
      </article>
      
      
      <div className='text-[3.4375rem] font-semibold text-center max-w-3xl mb-16'>
        How does Generative AI help with Product Photos?
      </div>
      <div className='text-4xl max-w-[68.9375rem] mb-32'>
        AI inspires and augments human creativity.
        It helps generate new ideas and designs. Meanwhile,
        it automates and accelerates the process of testing different ideas.
        With just a few clicks, you will see various versions of design.
        And you can modify and enhance the design from there much faster.
      </div>


      <article className='max-w-[68.9375rem] w-full mb-60'>
        <div className='text-center text-[3.4375rem] font-semibold pb-[122px]'>Questions?</div>
        <div className='flex flex-col w-full border-b-2 border-[#3D3D3D] mb-[30px]'>
          <div className='w-full flex justify-between cursor-pointer pb-10' onClick={ handleSetFirstCollapseSwitch }>
            <span className='text-4xl'>How to get started?</span>
            <Image
              className={`${firstCollapseSwitch ? 'rotate-180' : ''} cursor-pointer h-[1.5625rem] w-[3.125rem]`}
              src="/common/black-Inverted-triangle.png"
              alt=""
              width={0}
              height={0}
              sizes='100%'
              priority
            />
          </div>
          <div className='text-2xl'>
            {firstCollapseSwitch &&
              <div>
                <div className='py-6'>Yes, absolutely. A clean and great quality product photo will help a lot.</div>
                <div className='py-6'>When you create a new product, instead of uploading your product photo, just choose the option to let our team take the photos for you.</div>
              </div>}
          </div>
        </div>
        <div className='flex flex-col w-full border-b-2 border-[#3D3D3D] mb-[30px]'>
          <div className='w-full flex justify-between cursor-pointer pb-10' onClick={ handleSetSecondCollapseSwitch }>
            <span className='text-4xl'>Can you take product photos for me?</span>
            <Image
              className={`${secondCollapseSwitch ? 'rotate-180' : ''} cursor-pointer h-[1.5625rem] w-[3.125rem]`}
              src="/common/black-Inverted-triangle.png"
              alt=""
              width={0}
              height={0}
              sizes='100%'
              priority
            />
          </div>
          <div className='text-2xl'>
            {secondCollapseSwitch &&
              <div>
                <div className='py-6'>Yes, absolutely. A clean and great quality product photo will help a lot.</div>
                <div className='py-6'>When you create a new product, instead of uploading your product photo, just choose the option to let our team take the photos for you.</div>
              </div>}
          </div>
        </div>
        <div className='flex flex-col w-full border-b-2 border-[#3D3D3D] mb-[30px]'>
          <div className='w-full flex justify-between cursor-pointer pb-10' onClick={ handleSetThirdCollapseSwitch }>
            <span className='text-4xl'>Do you provide additional editing services?</span>
            <Image
              className={`${thirdCollapseSwitch ? 'rotate-180' : ''} cursor-pointer h-[1.5625rem] w-[3.125rem]`}
              src="/common/black-Inverted-triangle.png"
              alt=""
              width={0}
              height={0}
              sizes='100%'
              priority
            />
          </div>
          <div className='text-2xl'>
            {thirdCollapseSwitch &&
              <div>
                <div className='py-6'>Yes, absolutely. A clean and great quality product photo will help a lot.</div>
                <div className='py-6'>When you create a new product, instead of uploading your product photo, just choose the option to let our team take the photos for you.</div>
              </div>}
          </div>
        </div>
      </article>

      <footer className='bg-[--theme-darkblue] w-full text-white py-[3.5rem]'>
        
        <div className='text-center text-[2rem] font-semibold mb-[7.1875rem]'>AI ProShots</div>
        <article className='flex justify-around'>
          <div className='flex gap-x-[4.125rem] text-sm'>
            <span className='cursor-pointer'> Terms & Conditions </span>
            <span className='cursor-pointer'> Privacy Policy </span>
            <span className='cursor-pointer'> Sitemap </span>
            <span className='cursor-pointer'> Contact Us </span>
          </div>
          <span>© 2023 AI ProShots All Rights Reserved</span>
        </article>
      </footer>
    </div>
  )
}
